name: Lint

on:
  pull_request:
    branches: [master]

jobs:
  run_linter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: ESLint checker
        uses: ninosaurus/eslint-check@v5.3.1
      - run: npm install
      - run: npm run lint
